[package]
name = "dynprops_derive"
version = "0.1.0"
edition = "2018"

[lib]
name = "dynprops_derive"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }

[dev-dependencies]
dynprops = { path = ".." }